
default_platform(:android)

platform :android do
  desc "Lane for firebase app distribution"
  lane :firebase_distribution do
      sh "flutter clean"
      sh "flutter build apk --release --no-tree-shake-icons"
      firebase_app_distribution(
        app: "1:851705317705:android:673088b20b2268c3b03298",
        firebase_cli_token: "1//037Yd1NWNz9BaCgYIARAAGAMSNwF-L9IrDRo1H6ZkpwZZTGxNjMK4HbLSInJC-0RjSQ8iITTzm9ueR7ZL0QBmHWvfGY-JtQ3HBys",
        android_artifact_type: "APK",
        android_artifact_path: "../build/app/outputs/flutter-apk/app-release.apk",
        testers: "anas.mostafax0@gmail.com",
        release_notes: "New release of the app",
      )
  end
end
